[package]
name = "raklap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay-client-toolkit = "0.7.0"
smithay-clipboard = "0.6"
wayland-client = "0.30"

